import { app, Menu, nativeImage, Tray, type NativeImage } from 'electron'
import { join } from 'node:path'
import { APP_NAME } from '@shared/brand'
import type { OpenEventRequest } from '@shared/types'
import { settingsRepository } from '../database/settingsRepository'
import { reminderService } from './reminderService'

export interface TrayActions {
  show(): void
  openEvent(request: OpenEventRequest): void
  /** User-initiated refresh of all calendars (the app never syncs on its own). */
  refresh(): void
  quit(): void
}

/** Tray icon PNGs in /resources (generated by scripts/generate-icons.mjs). */
function trayImage(): NativeImage {
  const image = nativeImage.createEmpty()
  // Windows picks the best size for the current DPI.
  for (const [size, scale] of [
    [16, 1],
    [24, 1.5],
    [32, 2],
    [48, 3]
  ] as const) {
    const rep = nativeImage.createFromPath(join(app.getAppPath(), 'resources', `tray-${size}.png`))
    if (!rep.isEmpty()) image.addRepresentation({ scaleFactor: scale, buffer: rep.toPNG() })
  }
  return image
}

/**
 * System-tray icon. The app keeps running here when the window is closed, so
 * reminders still fire. Left-click opens the window; right-click shows the menu.
 */
class TrayService {
  private tray: Tray | null = null
  private actions: TrayActions | null = null
  private lastMenuKey = ''

  create(actions: TrayActions): void {
    if (this.tray) return
    this.actions = actions
    this.tray = new Tray(trayImage())
    this.tray.setToolTip(APP_NAME)
    this.tray.on('click', () => actions.show())
    this.tray.on('double-click', () => actions.show())
    this.update()
  }

  /** Rebuilds tooltip + menu (called on every reminder tick and after setting changes). */
  update(): void {
    if (!this.tray || !this.actions) return
    const actions = this.actions
    const settings = settingsRepository.get()
    const next = reminderService.nextEvent()
    const pausedUntil = settings.notificationsPausedUntil ? new Date(settings.notificationsPausedUntil) : null
    const paused = pausedUntil !== null && pausedUntil.getTime() > Date.now()

    const nextLabel = next
      ? `${new Date(next.start).toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })}  ${truncate(next.event.title, 40)}`
      : 'No more events in the next 24 hours'
    const notifState = !settings.notificationsEnabled
      ? 'Notifications off'
      : paused
        ? `Notifications paused until ${formatPause(pausedUntil!)}`
        : null

    // Called every 15 s: skip the native tooltip/menu rebuild when nothing changed.
    const menuKey = JSON.stringify([nextLabel, next?.event.id, notifState, settings.notificationsEnabled, paused])
    if (menuKey === this.lastMenuKey) return
    this.lastMenuKey = menuKey
    this.tray.setToolTip([APP_NAME, next ? `Next: ${nextLabel}` : null, notifState].filter(Boolean).join('\n'))

    const pause = (ms: number | 'tomorrow'): void => {
      const until =
        ms === 'tomorrow'
          ? (() => {
              const d = new Date()
              d.setDate(d.getDate() + 1)
              d.setHours(8, 0, 0, 0)
              return d
            })()
          : new Date(Date.now() + ms)
      settingsRepository.update({ notificationsPausedUntil: until.toISOString() })
      this.update()
    }

    this.tray.setContextMenu(
      Menu.buildFromTemplate([
        { label: `Open ${APP_NAME}`, click: () => actions.show() },
        { type: 'separator' },
        next
          ? { label: `Next: ${nextLabel}`, click: () => actions.openEvent({ eventId: next.event.id, startTime: next.event.startTime }) }
          : { label: nextLabel, enabled: false },
        { label: 'Refresh calendars', click: () => actions.refresh() },
        { type: 'separator' },
        ...(notifState ? [{ label: notifState, enabled: false } as const] : []),
        paused
          ? {
              label: 'Resume notifications',
              click: () => {
                settingsRepository.update({ notificationsPausedUntil: '' })
                this.update()
              }
            }
          : {
              label: 'Pause notifications',
              enabled: settings.notificationsEnabled,
              submenu: [
                { label: 'For 1 hour', click: () => pause(3_600_000) },
                { label: 'For 3 hours', click: () => pause(3 * 3_600_000) },
                { label: 'Until tomorrow (8:00)', click: () => pause('tomorrow') }
              ]
            },
        { type: 'separator' },
        { label: 'Quit', click: () => actions.quit() }
      ])
    )
  }

  destroy(): void {
    this.tray?.destroy()
    this.tray = null
  }
}

function truncate(text: string, max: number): string {
  return text.length > max ? `${text.slice(0, max - 1)}…` : text
}

function formatPause(date: Date): string {
  const sameDay = date.toDateString() === new Date().toDateString()
  const time = date.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })
  return sameDay ? time : `${date.toLocaleDateString(undefined, { weekday: 'short' })} ${time}`
}

export const trayService = new TrayService()
